
/* Drop Tables */

DROP TABLE RYANFARM.CART CASCADE CONSTRAINTS;
DROP TABLE RYANFARM.FREEBOARD CASCADE CONSTRAINTS;
DROP TABLE RYANFARM.ORDERINFO CASCADE CONSTRAINTS;
DROP TABLE RYANFARM.REVIEW CASCADE CONSTRAINTS;
DROP TABLE RYANFARM.GOODS CASCADE CONSTRAINTS;
DROP TABLE RYANFARM.QNA CASCADE CONSTRAINTS;
DROP TABLE RYANFARM.MEMBERINFO CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE RYANFARM.CART_NUM_SEQ;
DROP SEQUENCE RYANFARM.FREEBOARD_NUM_SEQ;
DROP SEQUENCE RYANFARM.QNA_NUM_SEQ;
DROP SEQUENCE RYANFARM.REVIEW_NUM_SEQ;




/* Create Sequences */

CREATE SEQUENCE RYANFARM.CART_NUM_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1 CACHE 20;
CREATE SEQUENCE RYANFARM.FREEBOARD_NUM_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1 CACHE 20;
CREATE SEQUENCE RYANFARM.QNA_NUM_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1 CACHE 20;
CREATE SEQUENCE RYANFARM.REVIEW_NUM_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1 CACHE 20;



/* Create Tables */

CREATE TABLE RYANFARM.CART
(
	CART_NUM number(10,0) NOT NULL,
	GCATEGORY varchar2(20 char) NOT NULL,
	GNAME varchar2(50 char) NOT NULL,
	GPRICE number(10,0) NOT NULL,
	GAMOUNT number(10,0) NOT NULL,
	GIMAGE1 varchar2(20 char) NOT NULL,
	GSIZE varchar2(10 char) NOT NULL,
	USERID varchar2(10 char) NOT NULL,
	GCODE varchar2(20 char) NOT NULL,
	CONSTRAINT SYS_C0011134 PRIMARY KEY (CART_NUM)
);


CREATE TABLE RYANFARM.FREEBOARD
(
	BOARD_NUM number(10,0) NOT NULL,
	TITLE varchar2(20 char) NOT NULL,
	AUTHOR varchar2(10 char) NOT NULL,
	CONTENT varchar2(4000 char),
	WRITEDAY date DEFAULT SYSDATE,
	IMAGE varchar2(20 char) DEFAULT '''X'' ',
	READCNT number(10,0) DEFAULT 0 ,
	USERID varchar2(10 char) NOT NULL,
	CONSTRAINT SYS_C0011138 PRIMARY KEY (BOARD_NUM)
);


CREATE TABLE RYANFARM.GOODS
(
	GCODE varchar2(20 char) NOT NULL,
	GCATEGORY varchar2(20 char) NOT NULL,
	GNAME varchar2(50 char) NOT NULL,
	GCONTENT varchar2(4000 char) NOT NULL,
	GPRICE number(10,0) NOT NULL,
	GIMAGE1 varchar2(20 char) NOT NULL,
	GIMAGE2 varchar2(20 char) NOT NULL,
	CONSTRAINT SYS_C0011117 PRIMARY KEY (GCODE)
);


CREATE TABLE RYANFARM.MEMBERINFO
(
	USERID varchar2(10 char) NOT NULL,
	PASSWD varchar2(10 char) NOT NULL,
	USERNAME varchar2(10 char) NOT NULL,
	POST1 varchar2(3 char) NOT NULL,
	POST2 varchar2(3 char) NOT NULL,
	ADDR1 varchar2(500 char) NOT NULL,
	ADDR2 varchar2(500 char) NOT NULL,
	PHONE1 varchar2(3 char) NOT NULL,
	PHONE2 varchar2(4 char) NOT NULL,
	PHONE3 varchar2(4 char) NOT NULL,
	EMAIL varchar2(20 char) NOT NULL,
	POINT number(10,0) DEFAULT 0,
	BUYCNT number(10,0) DEFAULT 0,
	JOINDAY date DEFAULT SYSDATE,
	CONSTRAINT SYS_C0011110 PRIMARY KEY (USERID)
);


CREATE TABLE RYANFARM.ORDERINFO
(
	ORDER_NUM number(10,0) NOT NULL,
	ORDERNAME number(10,0) NOT NULL,
	PHONE varchar2(15 char) NOT NULL,
	POST1 varchar2(3 char) NOT NULL,
	POST2 varchar2(3 char) NOT NULL,
	ADDR1 varchar2(500 char) DEFAULT '''X''',
	ADDR2 varchar2(500 char) NOT NULL,
	GNAME varchar2(50 char) NOT NULL,
	GPRICE number(10,0) NOT NULL,
	GSIZE varchar2(10 char) NOT NULL,
	GIMAGE varchar2(20 char) NOT NULL,
	PAYMETHOD varchar2(10 char) NOT NULL,
	GAMOUNT number(10,0) NOT NULL,
	ORDERDAY date DEFAULT SYSDATE
,
	GCODE varchar2(20 char) NOT NULL,
	USERID varchar2(10 char) NOT NULL,
	CONSTRAINT SYS_C0011152 PRIMARY KEY (ORDER_NUM)
);


CREATE TABLE RYANFARM.QNA
(
	QNA_NUM number(10,0) NOT NULL,
	USERNAME varchar2(10 char) NOT NULL,
	PHONE varchar2(15 char) NOT NULL,
	EMAIL varchar2(20 char),
	EMAIL2 varchar2(20 char),
	TITLE varchar2(50 char) NOT NULL,
	CONTENT varchar2(4000 char) NOT NULL,
	WRITEDAY date DEFAULT SYSDATE,
	STATE varchar2(10 char) DEFAULT '''처리 중''
',
	USERID varchar2(10 char) NOT NULL,
	CONSTRAINT SYS_C0011158 PRIMARY KEY (QNA_NUM)
);


CREATE TABLE RYANFARM.REVIEW
(
	REVIEW_NUM number(10,0) NOT NULL,
	USERNAME varchar2(10 char) NOT NULL,
	GRADE number(5,0) NOT NULL,
	IMAGE varchar2(20 char) DEFAULT '''x''',
	TITLE varchar2(50 char) NOT NULL,
	CONTENT varchar2(4000 char) NOT NULL,
	WRITEDAY date DEFAULT SYSDATE,
	GNAME varchar2(10 char) NOT NULL,
	GSIZE varchar2(10 char) NOT NULL,
	GCODE varchar2(20 char) NOT NULL,
	USERID varchar2(10 char) NOT NULL,
	CONSTRAINT SYS_C0011125 PRIMARY KEY (REVIEW_NUM)
);



/* Create Foreign Keys */

ALTER TABLE RYANFARM.CART
	ADD FOREIGN KEY (GCODE)
	REFERENCES RYANFARM.GOODS (GCODE)
;


ALTER TABLE RYANFARM.ORDERINFO
	ADD FOREIGN KEY (GCODE)
	REFERENCES RYANFARM.GOODS (GCODE)
;


ALTER TABLE RYANFARM.REVIEW
	ADD FOREIGN KEY (GCODE)
	REFERENCES RYANFARM.GOODS (GCODE)
;


ALTER TABLE RYANFARM.CART
	ADD FOREIGN KEY (USERID)
	REFERENCES RYANFARM.MEMBERINFO (USERID)
;


ALTER TABLE RYANFARM.FREEBOARD
	ADD FOREIGN KEY (USERID)
	REFERENCES RYANFARM.MEMBERINFO (USERID)
;


ALTER TABLE RYANFARM.ORDERINFO
	ADD FOREIGN KEY (USERID)
	REFERENCES RYANFARM.MEMBERINFO (USERID)
;


ALTER TABLE RYANFARM.QNA
	ADD FOREIGN KEY (USERID)
	REFERENCES RYANFARM.MEMBERINFO (USERID)
;


ALTER TABLE RYANFARM.REVIEW
	ADD FOREIGN KEY (USERID)
	REFERENCES RYANFARM.MEMBERINFO (USERID)
;



